version: '3.8'
services:
  api:
    image: node:18
    container_name: todo-app-2024-api
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    command: sh -c "npm install && npm run start:dev"