version: '3.8'
services:
  api:
    image: node:18
    container_name: todo-app-2024-api
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '4000:4000'
    env_file:
      - ./.env
    command: npm run start:dev
    depends_on:
      - db
  db:
    image: mysql:8
    platform: linux/amd64
    container_name: todo-app-2024-mysql
    environment:
      MYSQL_DATABASE: 'todo_db'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test1234'
      MYSQL_ROOT_PASSWORD: 'test1234'
    ports:
      - '3306:3306'
    volumes:
      - todo-db:/var/lib/mysql
volumes:
  todo-db:
